### PR TITLE
adds gemfile and test and development group

### PR DESCRIPTION
**Pull request by ice-king**

### CODE REVIEW

**Comment by makers-dev** [comment]
You need to put your pair partners

**Comment by makers-dev** [comment]
You need to add issues

**Comment by ice-king** [comment]
pair: @choose-goose

**Comment by makers-dev** [comment]
You need to add issues

**Comment by ice-king** [comment]
closes #1

**Comment by makers-dev** [comment]
Thanks for your submission, a coach will review it shortly

**Comment by silvabox** [comment]
:construction: you didn't run `bundle`

**Pull request merged**
